on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 8
        - java: 17
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - uses: coursier/cache-action@d1039466d0812d6370649b9afb02bbf5f646bacf # v6.4.3
    - run: sbt -v scalafmtSbtCheck scalafmtCheckAll "scalafixAll --check" test publishLocal scripted
    - if: always()
      run: rm -rf "$HOME/.ivy2/local" || true
